---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/contacts":
    post:
      summary: create contact
      responses:
        '200':
          description: successful
  "/api/v1/contacts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show contact
      responses:
        '200':
          description: successful
    put:
      summary: update contact
      responses:
        '200':
          description: successful
    delete:
      summary: delete contact
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
